### ISSUE TITLE
Chain does nothing

### ISSUE THREAD

**Issue by genmacg** [LaloMrtnz/Chain#4]
Hi,

I'm running Sketch 46 (44423) with Chain v0.9.1 on macOS Sierra 10.12.5.

Basically Chain does nothing. The Console doesn't log anything connected to Chain. 

I created a new file with two 100x100 rectangles named "white" and "black" on a 100x200 Artboard with background colours matching the rectangle names. File saved as "chain". White at 0,0 and black at 0,100. I select both rectangles, create a new chain with following settings: Hue, white is reference, Fill radio button selected, 0 in transformation field and Fill checkbox checked. Everything according to your video. Nothing happens.

Cheers, I hope the details help.

**Comment by LaloMrtnz** [comment]
Hi, @genmacg 
Based on your description and given the fact that the console is not displaying any errors, I believe that problem is the type of chain you are creating. 
Keep in mind that when you chain two layers, **the chain only affects the selected property** (hue/sat/bright/alpha) leaving the other ones intact. If you use white and black as your fill colors you will not be able to see a the changes because on both cases the _saturation_ is at 0 and so the property (hue) does not show on the color. I'm pretty sure that if you set both layers to let's say blue and red, and then run **_Update All Chains_**, the plugin will behave as expected. 

If you want to chain white and black, I would recommend using a Brightness chain on top of the hue (you can add multiple). 

I know it's not the most intuitive thing, but I'm working to make it easier to use and to implement on your workflow. 

Please let me know if this actually solves your problem or if we need to find another way to debug.

**Comment by genmacg** [comment]
Thx @LaloMrtnz, you are absolutely correct, thanks for pointing that out =)

While I'm at it, is there a way to show existing chains or is that a feature for the future?

cheers

**Comment by LaloMrtnz** [comment]
Great! Glad the problem was fixed. I'm closing the issue now. 

There's no way to show existing chains yet, but I'm working on a way to display that info. Do you like the option suggested on Issue #6 ?
